version: '2'

services:
  spark:
    image: docker.io/bitnami/spark:2.4.6
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
  spark-worker-1:
    image: docker.io/bitnami/spark:2.4.6
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  spark-worker-2:
    image: docker.io/bitnami/spark:2.4.6
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  livy:
    image: slj/livy
    container_name: livy
    links:
      - spark
      - spark-worker-1
      - spark-worker-2
    build:
      context: .
      dockerfile: Dockerfile.livy
    ports:
      - "8998:8998"
    volumes:
      - $PWD/jars:/opt/jars
    depends_on:
      - "spark"
      - "spark-worker-1"
      - "spark-worker-2"
  jupyter:
    image: slj/sparkmagic
    container_name: sparkmagic
    build:
      context: .
      dockerfile: Dockerfile.sparkmagic
      args:
        dev_mode: "false"
    ports:
      - "8888:8888"
    depends_on:
      - "livy"
    links:
      - livy
    environment:
      - JUPYTER_ENABLE_LAB=1
